[book]
authors = ["Carson Swoveland"]
language = "en"
multilingual = false
src = "src"
title = "Teaching Build Your Own Breadboard Computer"

[preprocessor]

[preprocessor.wavedrom]
command = "mdbook-wavedrom"

[output]

[output.html]
additional-js = ["wavedrom.min.js", "wavedrome-default.js"]
